{
 "title": "Elassandra",
 "description": "Monitoring Elassandra with Prometheus using JXM exporter",
 "tags": [
  "cassandra",
  "elasticsearch"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "release",
    "query": "label_values(up{app=\"elassandra\"}, release)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{app=\"elassandra\"}, cluster)"
   },
   {
    "name": "datacenter",
    "label": "datacenter",
    "query": "label_values(up{app=~\"elassandra\"}, datacenter)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{app=\"elassandra\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Nodes UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(elasticsearch_cluster_alivenodecount{cluster=\"$cluster\",datacenter=\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write\"} > 0"
    }
   ]
  },
  {
   "title": "ClientRead avg duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read\"} > 0"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"} / jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pending threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ParNew GC duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ParNew\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ParNew\"}[$interval])"
    }
   ]
  },
  {
   "title": "OldGen GC duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval])"
    }
   ]
  },
  {
   "title": "ES Index count",
   "type": "singlestat",
   "description": "Elasticsearch thread queue size",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (elasticsearch_index_indexstatuscode{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ES Docs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_indexshard_count{instance=\"$instance\",scope=\"docs\",index=\"\"}"
    }
   ]
  },
  {
   "title": "ES Index size",
   "type": "singlestat",
   "description": "Elasticsearch index size",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indexshard_sizeinbytes{instance=\"$instance\",index=~\".*\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "ES Segments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_indexshard_count{instance=\"$instance\",scope=\"segments\",index=\"\"}"
    }
   ]
  },
  {
   "title": "SSTable count",
   "type": "singlestat",
   "description": "Elasticsearch thread queue size",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_columnfamily_livesstablecount{instance=\"$instance\",keyspace=\"\"}"
    }
   ]
  },
  {
   "title": "Timeout exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts{clientrequest=~\"Write|Read\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(cassandra_connection_totaltimeouts{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables{clientrequest=~\"Read|Write\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "ES FieldData evictions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indexshard_evictions{cluster=\"$cluster\",scope=\"fieldData\",index=~\".+\"})"
    }
   ]
  },
  {
   "title": "ES FieldData evictions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indexshard_evictions{cluster=\"$cluster\",scope=\"fieldData\",index=~\".+\"})"
    }
   ]
  },
  {
   "title": "ES Thread Queues",
   "type": "singlestat",
   "description": "Elasticsearch thread queue size",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_node_threadpool_queue{instance=\"$instance\",name=~\".*\"})"
    }
   ]
  },
  {
   "title": "ES Threads",
   "type": "singlestat",
   "description": "Elasticsearch threadpool size",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_node_threadpool_threads{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ES Yellow index",
   "type": "singlestat",
   "description": "Elasticsearch number of yellow index",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (elasticsearch_index_indexstatuscode{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "ES Red index",
   "type": "singlestat",
   "description": "Elasticsearch number of red index",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (elasticsearch_index_indexstatuscode{instance=\"$instance\"} == 2)"
    }
   ]
  },
  {
   "title": "ES pending tasks",
   "type": "singlestat",
   "description": "Elasticsearch number of pending tasks",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_numberofpendingtasks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ES metadata.version",
   "type": "singlestat",
   "description": "Elasticsearch metadata.version",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_metadataversion{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Indexing req/s $instance",
   "type": "graph",
   "description": "Elasticsearch indexing operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indexshard_indextotal{instance=\"$instance\",scope=\"indexing\",index=~\".+\"}[$interval]) > 0",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Search req/s $instance",
   "type": "graph",
   "description": "Elasticsearch indexing operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indexshard_querytotal{instance=\"$instance\",scope=\"search\",index=~\".+\"}[$interval]) > 0",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Indexing mean latency (ms) $instance",
   "type": "graph",
   "description": "Elasticsearch indexing latency in ms",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(elasticsearch_indexshard_indextimeinmillis{instance=\"$instance\",index=\"\"}[$interval]) / idelta(elasticsearch_indexshard_indextotal{instance=\"$instance\",index=\"\"}[$interval])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Search mean latency (ms) $instance",
   "type": "graph",
   "description": "Elasticsearch search mean latency in ms",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(elasticsearch_indexshard_querytimeinmillis{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) / idelta(elasticsearch_indexshard_querytotal{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) > 0",
     "legendFormat": "{{query}}"
    },
    {
     "expr": "idelta(elasticsearch_indexshard_fetchtimeinmillis{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) / idelta(elasticsearch_indexshard_fetchtotal{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) > 0",
     "legendFormat": "{{fetch}}"
    },
    {
     "expr": "idelta(elasticsearch_indexshard_suggesttimeinmillis{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) / idelta(elasticsearch_indexshard_suggesttotal{instance=\"$instance\",scope=\"search\",index=\"\"}[$interval]) > 0",
     "legendFormat": "{{suggest}}"
    }
   ]
  },
  {
   "title": "Coordinator level stats (data can be R/W using other nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Write / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Write.*\"}[$interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Reads / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Read.*\"}[$interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",type=~\"Write.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests to R/W on current node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Writes \\ sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_table_writelatency_count{instance=~\"$instance\",keyspace!~\"system.*\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Reads \\ sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_table_readlatency_count{instance=~\"$instance\",keyspace!~\"system.*|eit\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Avg write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_mean{instance=~\"$instance\",keyspace!~\"system.*\"} > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Avg read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_readlatency_mean{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_readlatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Keyspace Range latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_rangelatency_mean{instance=\"$instance\"}",
     "legendFormat": "RangeLatency"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "GC count / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC avg time $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Heap usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"}",
     "legendFormat": "Used heap size"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}",
     "legendFormat": "Max heap size"
    }
   ]
  },
  {
   "title": "Non-Heap usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=\"$instance\"}",
     "legendFormat": "Used non-heap size"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",instance=\"$instance\"}",
     "legendFormat": "Commited non-heap size"
    }
   ]
  },
  {
   "title": "Memory Pool used $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Threads count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "Threads count"
    }
   ]
  },
  {
   "title": "Open file descriptors $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  { "title": "Requests errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Unavailable exceptions / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_unavailables[$interval]) > 0",
     "legendFormat": "{{clientrequest}}"
    }
   ]
  },
  {
   "title": "Timeout exceptions / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_timeouts[$interval]) > 0",
     "legendFormat": "{{clientrequest}}"
    }
   ]
  },
  {
   "title": "Connection timeouts / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_connection_totaltimeouts[$interval]) > 0",
     "legendFormat": "Connection timeouts"
    }
   ]
  },
  {
   "title": "Storage exceptions / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_storage_exceptions[$interval])",
     "legendFormat": "Expections"
    }
   ]
  },
  {
   "title": "Speculative retries / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_speculativeretries{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "DIsk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Top10 tables by size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_columnfamily_totaldiskspaceused{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load{instance=~\"$instance\"}",
     "legendFormat": "Total disk usage"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Top10 SSTables count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,cassandra_columnfamily_livesstablecount{keyspace=~\".+\",instance=~\"$instance\"}) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Pending tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}",
     "legendFormat": "Pending tasks"
    }
   ]
  },
  {
   "title": "Completed tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_completedtasks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Completed tasks"
    }
   ]
  },
  {
   "title": "Bytes compacted $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_bytescompacted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Bytes compacted"
    }
   ]
  },
  {
   "title": "Completed compactions $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_totalcompactionscompleted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Compactions completed"
    }
   ]
  },
  {
   "title": "SSTablesPerRead $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_sstablesperreadhistogram{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "Connected clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "Client count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=\"$instance\"}",
     "legendFormat": "Native"
    },
    {
     "expr": "cassandra_client_connectedthriftclients{instance=\"$instance\"}",
     "legendFormat": "Thrift"
    }
   ]
  },
  { "title": "Hinted handoff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Total hints / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_storage_totalhints{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "Total hints count"
    }
   ]
  },
  {
   "title": "Total hints in progress / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_storage_totalhintsinprogress{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "Total hints in progress"
    }
   ]
  },
  { "title": "Bloom filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 } },
  {
   "title": "False positives $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalsepositives{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "False ratio $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalseratio{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterdiskspaceused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "OffHeap memory used $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilteroffheapmemoryused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "Completed tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_threadpools_completedtasks{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Pending tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_pendingtasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Dropped messages / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_droppedmessage_dropped{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{droppedmessage}}"
    }
   ]
  },
  {
   "title": "Active tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_activetasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Total blocked tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_threadpools_totalblockedtasks{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Currently blocked tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_currentlyblockedtasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  { "title": "Key cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "KeyCache Hit Rate $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_hitrate{instance=\"$instance\"}",
     "legendFormat": "{{hit rate}}"
    }
   ]
  },
  {
   "title": "Cache size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 203 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_size{instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache hits / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_hits{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache requests / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_requests{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache entries $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_entries{instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  { "title": "Memtables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 217 } },
  {
   "title": "Top10 memtables by table size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_columnfamily_memtablelivedatasize{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Memtables columns count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtablecolumnscount{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total memtables size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtableonheapsize{keyspace=\"\",instance=~\"$instance\"}",
     "legendFormat": "OnHeap"
    },
    {
     "expr": "sum(cassandra_columnfamily_memtableoffheapsize{keyspace=\"\",instance=~\"$instance\"})",
     "legendFormat": "OffHeap"
    }
   ]
  },
  {
   "title": "Memtables switch count / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_memtableswitchcount{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "CQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 } },
  {
   "title": "CQL regular statements / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cql_regularstatementsexecuted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Regular statements"
    }
   ]
  },
  {
   "title": "CQL prepared statements $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 233 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cql_preparedstatementsexecuted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Prepared statements"
    }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 } },
  {
   "title": "Snapshots size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_snapshotssize{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  }
 ]
}